apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: k8s-demo
        image: drixmux/hello-world
        ports:
        - name: nodejs-port
          containerPort: 3000
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: k8s-demo
        image: drixmux/hello-world
        ports:
        - name: nodejs-port
          containerPort: 3000