apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    request:
      storage: 8Gi